---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.AppVersion }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-{{ .Chart.AppVersion }}
