apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp-project
  namespace: argocd
spec:
  destination:
    namespace: wp-project
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wp-project
    repoURL: https://sgoser.github.io/academy.project/Helm/wp-project/helm-releases/
    targetRevision: 0.0.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
