name: CICD. Create HELM chart. Argo App.

on:
  push:
    tags: 'chart-*'

env:
    # REQUIREMENTS
    # secrets.SLACK_TOKEN
    # secrets.BOT_GITHUB_TOKEN

    SLACK_CHANNEL_ID: 'C04LZC84A9X'
    GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    HELM_PATH : ./Helm/wp-project

jobs:
  helm:
    runs-on: ubuntu-latest
    outputs:
      out-job-status: ${{ job.status }}
      chart-version: ${{ steps.chart_v.outputs.chart_v }}
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          fetch-depth: '0'
      - 
        name: Test manifests
        continue-on-error: true
        uses: instrumenta/kubeval-action@master
        with: 
          files: ./Helm/wp-project/helm-source/templates
      - 
        name: Make chart version from tag (last 5 chars)
        id: chart_v
        run: |
          echo "chart_v=$(echo -n ${{  github.ref_name }} | tail -c 5)" >> $GITHUB_OUTPUT
      - 
        name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: ./Helm/wp-project
          target_dir: ./Helm/wp-project/helm-releases/
          branch: main
          linting: on
          charts_url: https://sgoser.github.io/academy.project/
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          chart_version: ${{ steps.chart_v.outputs.chart_v }}
      - 
        name: Update argo application yaml
        run: |
          git pull origin main
          sed -i "s/targetRevision:.*$/targetRevision: ${{ steps.chart_v.outputs.chart_v }}/" ./ArgoCD/argo-app-wp-project.yaml
          sed -i "s/^version:.*$/version: ${{ steps.chart_v.outputs.chart_v }}/" ./Helm/wp-project/helm-source/Chart.yaml
          git config --local user.email "github@github.com"
          git config --local user.name "GitHub Action"
          git add ./ArgoCD
          git add ./Helm/wp-project/helm-source/Chart.yaml
          git commit -m "New Chart version in Argo App YAML"
      -
        name: Push changes
        uses: ad-m/github-push-action@master

  slack:
    needs: [helm]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL_ID }}
          slack-message: |
            GitHub helm create result: ${{ needs.helm.outputs.out-job-status }}
            Helm was created with chart vesion: ${{ needs.helm.outputs.chart-version }} 
            and image taged as: v${{ needs.helm.outputs.chart-version }}
            Commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
            Action URL: ${{ env.GITHUB_WORKFLOW_URL }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}